#!/usr/bin/python3
import argparse

#from innerHTML import *
#from templateHTML import *
#from templateDocument import *
from generator import StaticSiteGenerator

website = StaticSiteGenerator('mariostoc.co')

## Command Line Argument Definitions
parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(dest="action", help='________________________')
subparsers.add_parser('clean', help='Removes previously published documents')
subparsers.add_parser('deploy', help='Walks the content directory and creates documents')
subparsers.add_parser('redeploy', help='Clean and deploys')
subparsers.add_parser('testpage', help='Creates testpage.html')
parser.parse_args(namespace=website)

## Let's do this
website.do()
