#!/usr/bin/python3
import os
import sys
from datetime import datetime, timedelta
from templateDocument import *
import subprocess


if len(sys.argv) < 2:
	## use any argument to skip the
	## connection with GitHub
	pull = subprocess.run(["git", "pull", "--quiet"])

prefixes = []
today = datetime.today()
delta = timedelta(days = (today.weekday() + 1))
sunday = (today - delta)
weekday = today.strftime('%a').lower()
microsecs = today.strftime('%f')

if delta.days == 7:
	prefixes.append(today.strftime('%Y%m%d'))
prefixes.append(sunday.strftime('%Y%m%d'))

directory = '/home/mstocco/mariostoc.co/content/traininglog'
for filename in os.listdir(directory):
	for prefix in prefixes:
		if filename.find(prefix) == 0:
			if filename.find('.icloud') > 1: continue
			
			basename = '%s/%s' % (directory, filename)
			documentURI = '/traininglog/%s' % filename[9:].split('.')[0]
			target = '/home/mstocco/mariostoc.co/docs%s' % documentURI
			webpage = TemplateDocument()
			webpage.lastModified = int(filename[:8])
			webpage.documentURI = documentURI
			webpage.handleMarkdown(basename)
		
			if len(sys.argv) > 1:
				print(filename)
				print(basename)
				print(documentURI)
				print(target)

			fileobj = open(target, 'w', encoding='utf-8')
			fileobj.write(webpage.tohtml())
			fileobj.close()
print('http://192.168.0.99%s?%s=%s' % (documentURI, weekday, microsecs))
