#!/usr/bin/python3
import argparse

#from innerHTML import *
#from templateHTML import *
#from templateDocument import *
from website import *

website = Website()

## Command Line Argument Definitions
parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(dest="action", help='________________________')
subparsers.add_parser('clean', help='Removes previously published documents')
subparsers.add_parser('publish', help='Walks the content directory and creates documents')
subparsers.add_parser('makeall', help='Clean and publish')
subparsers.add_parser('makecurrent', help='Just publish the current training week')
parser.parse_args(namespace=website)

## Let's do this
website.do()
